[variables]
NODE_VERSION = '22'

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@10.15.0 --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm start'