[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'npm install -g pnpm@10.15.0',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm start'