[phases.setup]
nixPkgs = ['nodejs_22', 'corepack']

[phases.install]
cmds = [
  'corepack enable',
  'corepack use pnpm@10.15.0',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm start'